import {calculate,iso,parts,todayLocal,lunarMonths,lunarToSolar,solarToLunar} from './age-logic.js';
import {readProfiles,saveProfile,removeProfile} from './profiles.js';
import {initPwaStatus} from './pwa-status.js';

const $=id=>document.getElementById(id);
const state={mode:'solar',lastBirth:null,lastResult:null,lastSettings:null,lastProfile:null,dirty:false,profiles:[],currentProfile:null,defaultSettings:null};
const solarYear=$('solar-year'),solarMonth=$('solar-month'),solarDay=$('solar-day');
const lunarYear=$('lunar-year'),lunarMonth=$('lunar-month'),lunarDay=$('lunar-day');
const target=$('target-age');
const DEFAULT_KEY='age-notebook.default.v1';
function selectedDefault(){const lunar=state.mode==='lunar';const [month,leap]=lunarMonth.value.split('-').map(Number);return {version:1,mode:state.mode,year:Number(lunar?lunarYear.value:solarYear.value),month:lunar?month:Number(solarMonth.value),day:Number(lunar?lunarDay.value:solarDay.value),leap:lunar&&Boolean(leap),targetAge:Number(target.value)};}
function sameSettings(a,b){return Boolean(a&&b)&&['mode','year','month','day','leap','targetAge'].every(key=>a[key]===b[key]);}
function defaultBirth(value){if(!value||value.version!==1||!['solar','lunar'].includes(value.mode)||![value.year,value.month,value.day,value.targetAge].every(Number.isInteger)||typeof value.leap!=='boolean')throw new Error('默认生日格式无效');return value.mode==='lunar'?lunarToSolar(value.year,value.month,value.day,value.leap):iso(value.year,value.month,value.day);}
function defaultStatus(message,exists){$('default-status').textContent=message;if(exists!==undefined)$('remove-default').hidden=!exists;}
function restoreDefault(){let raw;try{raw=localStorage.getItem(DEFAULT_KEY);}catch{defaultStatus('此浏览器无法读取默认生日，仍可手动计算。');return;}if(!raw)return;try{const value=JSON.parse(raw);const birth=defaultBirth(value);calculate(birth,todayLocal(),value.targetAge);
  state.defaultSettings=value;state.currentProfile=state.profiles.some(p=>p.id===value.profileId&&sameSettings(p.settings,value))?value.profileId:null;applySettings(value);renderProfilePicker();
  defaultStatus('已载入默认生日；修改后可重新设为默认。',true);run(birth,false);
}catch{defaultStatus('默认生日未能载入，请重新设置。',true);}}
function saveDefault(){try{const settings=selectedDefault();const profile=state.profiles.find(p=>p.id===state.currentProfile);const value={...settings,profileId:sameSettings(profile?.settings,settings)?profile.id:null};const birth=defaultBirth(value);calculate(birth,todayLocal(),value.targetAge);try{localStorage.setItem(DEFAULT_KEY,JSON.stringify(value));}catch{defaultStatus('此浏览器无法保存，请检查是否允许网站存储。');return;}state.defaultSettings=value;state.currentProfile=value.profileId;renderProfilePicker();defaultStatus('默认生日已保存，下次打开会自动计算。',true);run(birth,false);storyNotice('已设为默认生日，下次打开直接查看年龄。');}catch(error){showError(error.message);}}
function removeDefault(){try{localStorage.removeItem(DEFAULT_KEY);state.defaultSettings=null;defaultStatus('已取消默认生日，可随时重新设置。',false);storyNotice('已取消默认生日。');}catch{defaultStatus('未能取消默认，请检查是否允许网站存储。');}}
function storyNotice(message){$('story-notice').textContent=message;$('story-notice').hidden=!message;}
function setEditor(open,focus=false){$('birthday-editor').hidden=!open;$('edit-birthday').hidden=open;$('edit-birthday').setAttribute('aria-expanded',String(open));$('cancel-edit').hidden=!state.lastResult;$('calculate-label').textContent=state.lastResult?'更新时光档案':'开启我的时光档案';if(open&&focus){$('birthday-editor').scrollIntoView({behavior:'smooth',block:'start'});(state.mode==='solar'?solarYear:lunarYear).focus({preventScroll:true});}}
function applySettings(value){target.value=String(value.targetAge);setMode(value.mode);if(value.mode==='solar'){solarYear.value=String(value.year);solarMonth.value=String(value.month);updateSolarDays();solarDay.value=String(value.day);}else{lunarYear.value=String(value.year);updateLunarMonths();lunarMonth.value=`${value.month}-${Number(value.leap)}`;updateLunarDays();lunarDay.value=String(value.day);}if(defaultBirth(selectedDefault())!==defaultBirth(value))throw new Error('保存的生日无法在当前日期范围内载入');}
function markBirthdayEdited(){hideError();storyNotice('');if(state.defaultSettings)defaultStatus('当前修改尚未设为默认；原来的默认生日仍保留。',true);if(!state.lastResult)return;state.dirty=true;$('results').hidden=true;$('pending-message').hidden=false;$('copy-button').disabled=true;$('calculate-label').textContent='更新时光档案';}
function cancelEditing(){if(!state.lastSettings)return;state.currentProfile=state.lastProfile;applySettings(state.lastSettings);renderProfilePicker();state.dirty=false;$('pending-message').hidden=true;run(state.lastBirth,false);storyNotice('');window.scrollTo({top:0,behavior:'smooth'});}
function loadProfileList(){try{state.profiles=readProfiles(localStorage);}catch{state.profiles=[];$('profile-message').textContent='档案未能载入，已有数据会保留。';}renderProfilePicker();}
function renderProfilePicker(){const current=state.profiles.find(p=>p.id===state.currentProfile);fill($('profile-picker'),[['','临时生日'],...state.profiles.map(p=>[p.id,p.name])],current?.id||'');$('profile-picker-row').hidden=!state.profiles.length;$('profile-name').value=current?.name||'';$('remove-profile').hidden=!current;$('profile-summary').textContent=current?'编辑生日档案':'保存生日档案';}
function activateProfile(id){if(!id){state.currentProfile=null;renderProfilePicker();setEditor(true,true);markBirthdayEdited();$('profile-editor').open=true;return;}try{state.profiles=readProfiles(localStorage);const profile=state.profiles.find(p=>p.id===id);if(!profile)throw new Error('未找到该生日档案');const birth=defaultBirth(profile.settings);calculate(birth,todayLocal(),profile.settings.targetAge);state.currentProfile=id;applySettings(profile.settings);renderProfilePicker();run(birth,false);storyNotice(`正在查看：${profile.name}`);window.scrollTo({top:0,behavior:'smooth'});}catch(error){showFormError(error.message);setEditor(true,true);}}
function saveCurrentProfile(){try{const settings=selectedDefault();const birth=defaultBirth(settings);calculate(birth,todayLocal(),settings.targetAge);const profile=saveProfile(localStorage,{...(state.currentProfile?{id:state.currentProfile}:{}),name:$('profile-name').value,settings});state.currentProfile=profile.id;state.profiles=readProfiles(localStorage);renderProfilePicker();let message=`生日档案“${profile.name}”已保存。`;if(state.defaultSettings?.profileId===profile.id){try{const value={...settings,profileId:profile.id};localStorage.setItem(DEFAULT_KEY,JSON.stringify(value));state.defaultSettings=value;defaultStatus('默认生日已同步更新。',true);}catch{message+=' 默认生日未能同步，请重新设置。';}}$('profile-message').textContent='';run(birth,false);storyNotice(message);}catch(error){showFormError(error.message);}}
function removeCurrentProfile(){const profile=state.profiles.find(p=>p.id===state.currentProfile);if(!profile||!confirm(`删除“${profile.name}”的生日档案？`))return;try{removeProfile(localStorage,profile.id);state.currentProfile=null;if(state.lastProfile===profile.id)state.lastProfile=null;state.profiles=readProfiles(localStorage);renderProfilePicker();if(state.lastResult){const r=state.lastResult;$('current-birth').textContent=state.lastSettings?.mode==='lunar'?'农历 '+r.lunar.year+'年'+r.lunar.monthName+r.lunar.dayName:'公历 '+briefDate(r.birth);}let message='生日档案已删除。';if(state.defaultSettings?.profileId===profile.id){try{localStorage.removeItem(DEFAULT_KEY);state.defaultSettings=null;defaultStatus('关联的默认生日已取消。',false);}catch{message+=' 请手动取消关联的默认生日。';}}storyNotice(message);hideError();}catch(error){showFormError(error.message);}}
function fill(el,items,value){el.replaceChildren(...items.map(([v,label])=>{const o=document.createElement('option');o.value=String(v);o.textContent=label;return o;}));if(value!==undefined&&items.some(([v])=>String(v)===String(value)))el.value=String(value);}
function range(a,b){return Array.from({length:b-a+1},(_,i)=>a+i);}
function localDate(s){const p=parts(s);return `${p.year}年${String(p.month).padStart(2,'0')}月${String(p.day).padStart(2,'0')}日`;}
function briefDate(s){const p=parts(s);return `${p.year}.${String(p.month).padStart(2,'0')}.${String(p.day).padStart(2,'0')}`;}
function updateSolarDays(){const y=Number(solarYear.value),m=Number(solarMonth.value),old=solarDay.value;const max=new Date(Date.UTC(y,m,0)).getUTCDate();const min=y===1900&&m===1?31:1;fill(solarDay,range(min,max).map(d=>[d,`${d}日`]),Math.min(Math.max(Number(old)||min,min),max));}
function updateLunarDays(){const selected=lunarMonths(Number(lunarYear.value)).find(m=>`${m.month}-${Number(m.leap)}`===lunarMonth.value);if(!selected)return;const old=Number(lunarDay.value)||1;fill(lunarDay,range(1,selected.days).map(d=>[d,`${d}日`]),Math.min(old,selected.days));}
function updateLunarMonths(){const old=lunarMonth.value,month=Number(old.split('-')[0])||1;const list=lunarMonths(Number(lunarYear.value));fill(lunarMonth,list.map(m=>[`${m.month}-${Number(m.leap)}`,m.label]),old);if(!list.some(m=>`${m.month}-${Number(m.leap)}`===old))lunarMonth.value=`${month}-0`;updateLunarDays();}
function setMode(mode){state.mode=mode;for(const m of ['solar','lunar']){const active=m===mode;$(m+'-tab').classList.toggle('active',active);$(m+'-tab').setAttribute('aria-selected',String(active));$(m+'-fields').hidden=!active;}hideError();}
function hideError(){$('form-error').hidden=true;}
function showFormError(message){$('form-error').textContent=message;$('form-error').hidden=false;}
function showError(message){state.dirty=Boolean(state.lastResult);$('results').hidden=true;$('pending-message').hidden=!state.lastResult;showFormError(message);setEditor(true);}
function resultText(r){const l=r.lunar;return [
  `周岁：${r.age}岁`,`虚岁：${r.virtualAge}岁`,`精确年龄：${r.precise.years}岁 ${r.precise.months}个月 ${r.precise.days}天`,`生肖：${r.animal}`,
  `星座：${r.zodiac}`,`公历出生日期：${localDate(r.birth)}`,`农历出生日期：${l.year}年${l.monthName}${l.dayName}（${r.ganzhi}）`,
  `下次公历生日：${localDate(r.nextSolar.date)}，还有${r.nextSolar.days}天，${r.nextSolar.weekday}`,
  `下次农历生日：${r.nextLunar.label} / 公历${localDate(r.nextLunar.date)}，还有${r.nextLunar.days}天，${r.nextLunar.weekday}`,
  `生活天数：${r.lifeDays}天`,`时光进度：${r.progress.toFixed(1)}%（目标${r.targetAge}岁）`,r.nextSolar.note,r.nextLunar.note].filter(Boolean).join('\n');}
function render(r){$('results').hidden=false;$('as-of').textContent=briefDate(r.today);$('age-years').textContent=r.age;$('precise-age').textContent=`准确地说，你已经 ${r.precise.years} 岁 ${r.precise.months} 个月 ${r.precise.days} 天`;
  $('virtual-age').textContent=`${r.virtualAge} 岁`;$('life-days').textContent=`${r.lifeDays.toLocaleString('zh-CN')} 天`;$('identity').textContent=`${r.animal} · ${r.zodiac}`;
  for(const [kind,next] of [['solar',r.nextSolar],['lunar',r.nextLunar]]){$(kind+'-count').textContent=next.days;$(kind+'-next').textContent=`${briefDate(next.date)} · ${next.weekday}`;$(kind+'-note').textContent=next.note;$(kind+'-note').hidden=!next.note;}
  $('solar-birth').textContent=localDate(r.birth);$('lunar-birth').textContent=`${r.lunar.year}年${r.lunar.monthName}${r.lunar.dayName}`;$('ganzhi-birth').textContent=r.ganzhi;$('zodiac-birth').textContent=`${r.animal}年生 · ${r.zodiac}`;
  $('progress-caption').textContent=`${r.age} / ${r.targetAge} 岁`;$('progress-number').textContent=`${r.progress.toFixed(1)}%`;$('progress-fill').style.width=`${r.progress}%`;$('copy-button').textContent='复制结果';
  $('copy-button').disabled=false;$('intro').hidden=true;$('dashboard-controls').hidden=false;document.querySelector('.app-shell').classList.add('has-story');
  const profile=state.profiles.find(p=>p.id===state.currentProfile);const profileLabel=profile?(sameSettings(profile.settings,state.lastSettings)?profile.name+' · ':'临时修改 · '):'';$('current-birth').textContent=`${profileLabel}${state.lastSettings?.mode==='lunar'?'农历 '+r.lunar.year+'年'+r.lunar.monthName+r.lunar.dayName:'公历 '+briefDate(r.birth)}`;
  renderBirthdayGreeting(r);
}
function renderBirthdayGreeting(r){const b=parts(r.birth),t=parts(r.today),solarDay=Math.min(b.day,new Date(Date.UTC(t.year,b.month,0)).getUTCDate());const solar=iso(t.year,b.month,solarDay)===r.today;const lunarToday=solarToLunar(r.today),options=lunarMonths(lunarToday.year),birthLunar=r.lunar;const leap=birthLunar.leap&&options.some(m=>m.month===birthLunar.month&&m.leap);const birthdayMonth=options.find(m=>m.month===birthLunar.month&&m.leap===leap);const lunar=lunarToday.month===birthLunar.month&&lunarToday.leap===leap&&lunarToday.day===Math.min(birthLunar.day,birthdayMonth.days);$('birthday-greeting').hidden=!(solar||lunar);$('birthday-greeting-text').textContent=`今天是你的${solar&&lunar?'公历和农历':solar?'公历':'农历'}生日，愿新的一岁有更多热爱。`;}
function run(birth,scroll=true,collapse=true){try{const r=calculate(birth,todayLocal(),Number(target.value));state.lastBirth=birth;state.lastResult=r;state.lastSettings=selectedDefault();state.lastProfile=state.currentProfile;state.dirty=false;hideError();$('pending-message').hidden=true;render(r);if(collapse)setEditor(false);else $('cancel-edit').hidden=false;if(scroll)window.scrollTo({top:0,behavior:'smooth'});return true;}catch(e){showError(e.message);return false;}}
function refreshToday(){const today=todayLocal();$('header-date').textContent=briefDate(today);const maxYear=Math.min(parts(today).year,2100);if(solarYear.options[0]?.value!==String(maxYear)){fill(solarYear,range(1900,maxYear).reverse().map(y=>[y,`${y} 年`]),solarYear.value);fill(lunarYear,range(1900,maxYear).reverse().map(y=>[y,`${y} 年`]),lunarYear.value);}if(state.lastBirth&&!state.dirty&&state.lastResult?.today!==today)run(state.lastBirth,false,false);}
function scheduleMidnight(){const now=new Date(),midnight=new Date(now);midnight.setHours(24,0,0,50);setTimeout(()=>{refreshToday();scheduleMidnight();},Math.max(50,midnight.getTime()-now.getTime()));}
function init(){const today=todayLocal();$('header-date').textContent=briefDate(today);const maxYear=Math.min(parts(today).year,2100);
  fill(solarYear,range(1900,maxYear).reverse().map(y=>[y,`${y} 年`]),2000);fill(solarMonth,range(1,12).map(m=>[m,`${m} 月`]),1);updateSolarDays();
  fill(lunarYear,range(1900,maxYear).reverse().map(y=>[y,`${y} 年`]),2000);updateLunarMonths();fill(target,range(1,150).map(n=>[n,`${n} 岁`]),80);
  solarYear.addEventListener('change',()=>{updateSolarDays();if(state.mode==='solar')markBirthdayEdited();});solarMonth.addEventListener('change',()=>{updateSolarDays();if(state.mode==='solar')markBirthdayEdited();});solarDay.addEventListener('change',()=>{if(state.mode==='solar')markBirthdayEdited();});lunarYear.addEventListener('change',()=>{updateLunarMonths();if(state.mode==='lunar')markBirthdayEdited();});lunarMonth.addEventListener('change',()=>{updateLunarDays();if(state.mode==='lunar')markBirthdayEdited();});lunarDay.addEventListener('change',()=>{if(state.mode==='lunar')markBirthdayEdited();});
  $('solar-tab').addEventListener('click',()=>{if(state.mode!=='solar'){setMode('solar');markBirthdayEdited();}});$('lunar-tab').addEventListener('click',()=>{if(state.mode!=='lunar'){setMode('lunar');markBirthdayEdited();}});
  $('age-form').addEventListener('submit',e=>{e.preventDefault();try{storyNotice('');run(defaultBirth(selectedDefault()));}catch(error){showError(error.message);}});
  $('save-default').addEventListener('click',saveDefault);$('remove-default').addEventListener('click',removeDefault);
  $('edit-birthday').addEventListener('click',()=>{setEditor(true,true);storyNotice('');});$('cancel-edit').addEventListener('click',cancelEditing);
  $('profile-picker').addEventListener('change',()=>activateProfile($('profile-picker').value));$('new-profile').addEventListener('click',()=>{state.currentProfile=null;renderProfilePicker();setEditor(true);markBirthdayEdited();$('profile-editor').open=true;$('profile-name').focus();});$('save-profile').addEventListener('click',saveCurrentProfile);$('remove-profile').addEventListener('click',removeCurrentProfile);
  target.addEventListener('change',()=>{if(state.defaultSettings)defaultStatus('时光目标已修改；重新设为默认后，下次打开会保留。',true);if(state.lastBirth&&!state.dirty)run(state.lastBirth,false,false);});
  $('clear-button').addEventListener('click',()=>{state.lastBirth=null;state.lastResult=null;state.lastSettings=null;state.dirty=false;$('results').hidden=true;$('pending-message').hidden=true;$('intro').hidden=false;$('dashboard-controls').hidden=true;document.querySelector('.app-shell').classList.remove('has-story');setEditor(true);hideError();window.scrollTo({top:0,behavior:'smooth'});});
  $('copy-button').addEventListener('click',async()=>{if(!state.lastResult||state.dirty)return;try{await navigator.clipboard.writeText(resultText(state.lastResult));$('copy-button').textContent='已复制 ✓';}catch{const text=resultText(state.lastResult);const el=document.createElement('textarea');el.value=text;document.body.append(el);el.select();const ok=document.execCommand('copy');el.remove();$('copy-button').textContent=ok?'已复制 ✓':'复制失败';}});
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshToday();});
  loadProfileList();
  restoreDefault();
  scheduleMidnight();initPwaStatus();
}
init();
